url: "https://lissydev.home.kg" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "lissy's website"
description: "Lissy's personal website"

collections:
    projects:
        output: true
    socials:
        output: true
    

tiny_projects:
    -
        title: ChromeDinoTractor
        host: github
        link: https://github.com/Xgames123/ChromeDinoTractor
        image: https://raw.githubusercontent.com/Xgames123/ChromeDinoTractor/main/Assets/Icon.gif
        status: canceled
        hasdemo: true
        
        platform_web: true


