url: "https://lissydev.home.kg" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "lissy's website"
description: "Lissy's personal website"

collections:
    projects:
        output: true
    socials:
        output: true


