url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "lissy's website"


projects:
    -
        title: Primitier modding framework
        platform: github
        link: https://github.com/Xgames123/PrimitierModdingFramework
        image: https://raw.githubusercontent.com/Xgames123/PrimitierModdingFramework/main/Documentation/PMFIconV2.png
        status: paused
        hasdemo: true
        
    - 
        title: Primitier mod manager
        platform: github
        link: https://github.com/Xgames123/PrimitierModManager
        image: https://raw.githubusercontent.com/Xgames123/PrimitierModdingFramework/main/Documentation/PMFIconV2.png
        status: paused
        hasdemo: true
    
    - 
        title: Primitier multiplayer mod
        platform: github
        link: https://github.com/Xgames123/PrimitierModManager
        image: https://raw.githubusercontent.com/Xgames123/PrimitierModdingFramework/main/Documentation/PMFIconV2.png
        status: paused
        hasdemo: false
        
    -
        title: Tiny village
        platform: itch
        link: https://lissydev.itch.io/tiny-village
        image: https://img.itch.zone/aW1hZ2UvMTE0OTUzNy82ODE2Mzk5LnBuZw==/original/6HZr%2BY.png
        status: canceled
        hasdemo: true
        
    -
        title: ChromeDinoTractor
        platform: github
        link: https://github.com/Xgames123/ChromeDinoTractor
        image: https://raw.githubusercontent.com/Xgames123/ChromeDinoTractor/main/Assets/Icon.gif
        status: canceled
        hasdemo: true
        
    -
        title: Tanks.io
        platform: itch
        link: https://lissydev.itch.io/tanksio
        image: https://img.itch.zone/aW1hZ2UvNTM1NzIzLzI5MjMyMzYucG5n/794x1000/XFn03Z.png
        status: canceled
        hasdemo: true
        
    

tiny_projects:
    -
        title: Primitier modding framework
        platform: github
        link: https://github.com/Xgames123/PrimitierModdingFramework
        image: https://raw.githubusercontent.com/Xgames123/PrimitierModdingFramework/main/Documentation/PMFIconV2.png
        status: paused


#usernames

github_username: xgames123
itch_username: lissydev
twitter_username: thereallissydev

discord_id: 621724325845663744
discord_username: lissy<3#6869

vrc_id: usr_a3683a1d-d328-46b0-94b2-61fa42b69c2e
vrc_username: lissydev


