url: "https://xgames123.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Redirect site"
description: "The site to redirect to when something goes wrong at ldev.eu.org"




